services:
  - type: web
    name: paint-website-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python init_db.py && gunicorn app.main:app --bind 0.0.0.0:$PORT --worker-class uvicorn.workers.UvicornWorker
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: SUPERADMIN_RESET_KEY
        value: "MARSSLcreations"
      - key: DATABASE_URL
        value: "postgresql://postgres.llrxqxofetmdbxbkbpeu:R1sKe51on9TifopP@aws-0-ap-south-1.pooler.supabase.com:6543/postgres"
      - key: CLOUDINARY_CLOUD_NAME
        value: "duxgtkuq8"
      - key: CLOUDINARY_API_KEY
        value: "216618683422457"
      - key: CLOUDINARY_API_SECRET
        value: "tuKgb8LdO-ws700DmAh83vcXBDM"
      - key: USE_CLOUDINARY
        value: "true"